services:
  ollama:
    image: ollama/ollama
    ports: 
    - 11434:11434
    volumes:
      - ollama_volume:/root/.ollama

  ollama-pull-model:
    image: ollama/ollama
    volumes:
      - ollama_volume:/root/.ollama
    entrypoint: /bin/sh
    command: -c "ollama serve & sleep 5 && ollama pull llama3.2:3b"
    depends_on:
      - ollama

  db:
    image: mariadb:11.7.2-ubi9
    volumes:
      - ./mariadb_data/:/var/lib/mysql:Z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - 3306:3306

  
  backend:
    build:
      context: .  
      dockerfile: backend/Dockerfile
    ports:
      - "8003:8003"
    container_name: backend 
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile  
    ports:
      - "8004:8004"
    container_name: frontend 
    depends_on:
    - backend 

volumes:
  ollama_volume:
 
